### ISSUE TITLE
break out Annotags into submodule?

### ISSUE THREAD

**Issue by JonathanReeve** [JonathanReeve/JonathanReeve.github.io#11]

**Comment by BigBlueHat** [comment]
:+1: would love to see this project get some traction. :smiley:

**Comment by BigBlueHat** [comment]
@JonathanReeve can I help you do this? :smile_cat:

**Comment by JonathanReeve** [comment]
@BigBlueHat, thanks for the reminder! I'd been meaning to do this for ages, but just never got around to it. You can find the submodule now at https://github.com/JonathanReeve/annotags. Feel free to help me turn Annotags into its own website, if you want. I really want to do that, but have had less and less time these days.
